# Generated by Django 5.1.5 on 2025-04-26 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trivia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("difficulty", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="trivia_images/")),
            ],
        ),
        migrations.CreateModel(
            name="TriviaScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("last_played", models.DateTimeField(auto_now=True)),
                (
                    "trivia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trivias.trivia"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "trivia")},
            },
        ),
    ]
