# Generated by Django 5.1.5 on 2025-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triviacategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="trivia_images/"),
        ),
        migrations.AlterField(
            model_name="triviacategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
