# Generated by Django 5.1.5 on 2025-04-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0002_trivia_url_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviascore',
            name='last_played',
        ),
    ]
