# Generated by Django 5.1.5 on 2025-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivias', '0003_remove_triviascore_last_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviascore',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
